name: on_prerelease
on:
  release:
    types:
      - prereleased
permissions:
  contents: read
jobs:
  check-version:
    runs-on: ubuntu-latest
    name: Check version in Cargo.toml
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Check if Cargo.toml version matches pre-release tag
        run: |
          NEWRELIC_AUTH_VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml)
          if [ "${NEWRELIC_AUTH_VERSION}" != "${{ github.event.release.tag_name }}" ]; then
            echo "Package version specified in Cargo.toml (${NEWRELIC_AUTH_VERSION}) differs from tag (${{ github.event.release.tag_name }}), exiting"
            exit 1
          fi

  build-image:
    name: Build and Push container image
    needs: [ check-version ]
    uses: ./.github/workflows/component_image.yml
    with:
      image-tag: ${{ github.event.release.tag_name }}-rc
      push: true
    secrets: inherit

  security-scan:
    name: Security scan
    needs: [ build-image ]
    uses: ./.github/workflows/component_image_security.yml
    with:
      image-tag: ${{ github.event.release.tag_name }}-rc
    secrets: inherit

  check-system-identity-endpoints-us:
    name: Check system identity endpoints (US)
    uses: ./.github/workflows/component_check_system_identity_endpoints.yml
    with:
      environment: "us"
    secrets:
      client_id: ${{ secrets.SYSTEM_IDENTITY_CHECKS_CLIENT_ID_US }}
      organization_id: ${{ secrets.SYSTEM_IDENTITY_CHECKS_ORGANIZATION_ID_US }}
      private_key_pem: ${{ secrets.SYSTEM_IDENTITY_CHECKS_PRIVATE_KEY_PEM_US }}

  build-binaries-linux:
    runs-on: ubuntu-latest
    name: Build/Push binaries linux
    needs: [ check-version ]
    permissions:
      # required to upload assets
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Obtain Rust version from project
        run: |
          RUST_VERSION=$(grep "rust-version" Cargo.toml | cut -d "=" -f2 | tr -d "[:space:]")
          echo "RUST_VERSION=${RUST_VERSION}" >> $GITHUB_ENV

      - name: Install Rust ${{ env.RUST_VERSION }}
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: >-
            aarch64-unknown-linux-musl,
            x86_64-unknown-linux-musl

      - name: Install Zig
        uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2

      - uses: taiki-e/install-action@a37010ded18ff788be4440302bd6830b1ae50d8b # v2.68.25
        with:
          tool: cargo-zigbuild@0.20.1

      - name: Build newrelic auth cli
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Build Linux targets
          cargo zigbuild --release --target "aarch64-unknown-linux-musl"
          cargo zigbuild --release --target "x86_64-unknown-linux-musl" 
          
          # Prepare Linux binaries
          chmod +x ./target/aarch64-unknown-linux-musl/release/newrelic-auth-cli
          chmod +x ./target/x86_64-unknown-linux-musl/release/newrelic-auth-cli
          tar -czf newrelic-auth-cli_arm64.tar.gz -C ./target/aarch64-unknown-linux-musl/release newrelic-auth-cli
          tar -czf newrelic-auth-cli_amd64.tar.gz -C ./target/x86_64-unknown-linux-musl/release newrelic-auth-cli

          # Upload all binaries
          gh release upload ${{ github.event.release.tag_name }} newrelic-auth-cli_arm64.tar.gz
          gh release upload ${{ github.event.release.tag_name }} newrelic-auth-cli_amd64.tar.gz

  build-binaries-windows:
    runs-on: ubuntu-latest
    name: Build/Push binaries windows
    needs: [ check-version ]
    permissions:
      # required to upload assets
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Obtain Rust version from project
        run: |
          RUST_VERSION=$(grep "rust-version" Cargo.toml | cut -d "=" -f2 | tr -d "[:space:]")
          echo "RUST_VERSION=${RUST_VERSION}" >> $GITHUB_ENV

      - name: Install Rust ${{ env.RUST_VERSION }}
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: x86_64-pc-windows-msvc

      - name: Install cargo-xwin
        run: |
          cargo install --locked cargo-xwin --force

      - name: Install Windows cross-compilation dependencies
        run: |
          sudo apt-get install -y llvm

      - name: Build newrelic auth cli
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Build Windows targets
          cargo xwin build --release --target "x86_64-pc-windows-msvc" 
          
          # Prepare Windows binaries (zip format)
          zip newrelic-auth-cli_windows_amd64.zip ./target/x86_64-pc-windows-msvc/release/newrelic-auth-cli.exe

          # Upload all binaries
          gh release upload ${{ github.event.release.tag_name }} newrelic-auth-cli_windows_amd64.zip

  notify-failure:
    if: ${{ failure() }}
    needs: [ build-image, check-system-identity-endpoints-us, build-binaries-linux, build-binaries-windows ]
    runs-on: ubuntu-latest
    steps:
      - name: Notify failure via Slack
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          payload: |
            {
              "text": ":warning: [Pre-release failed for `newrelic-auth-rs`] @hero check <${{ env.GITHUB_JOB_URL }}>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.AC_SLACK_WEBHOOK }}
          GITHUB_JOB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
